/*
* groupServer_proc.c: implementation of the
* remote procedure "printmessage"
*/

#include <stdio.h>
#include "groupServer.h" /* msg.h generated by rpcgen */

int * join_1_svc(char * ip_addr, int port_num, struct svc_req *req) {
  static int result;

  result = 1;
  return (&result);
}

int * leave_1_svc(char * ip_addr, int port_num, struct svc_req *req) {
  static int result;

  result = 1;
  return (&result);
}

int * subscribe_1_svc(char * ip_addr, int port_num, char * artcile,
                      struct svc_req *req) {
  static int result;

  result = 1;
  return (&result);
}

int * unsubscribe_1_svc(char * ip_addr, int port_num, char * article,
                        struct svc_req *req) {
  static int result;

  result = 1;
  return (&result);
}

int * publish_1_svc(char * article, char * ip_addr, int port_num,
                    struct svc_req *req) {
   static int result;

   result = 1;
   return (&result);
}

int * ping_1_svc(struct svc_req *req) {
  static int result;
  result = 1;
  return (&result);
}
